# Generated by Django 3.2.10 on 2021-12-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='convert_min_left',
            field=models.IntegerField(default=1000, verbose_name='How many minutes of video user can convert'),
        ),
    ]
