# Generated by Django 3.2.10 on 2021-12-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_convert_min_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='convert_min_left',
            field=models.FloatField(default=1000, verbose_name='How many minutes of video user can convert'),
        ),
    ]
