# Generated by Django 3.2.10 on 2021-12-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoraw',
            name='req_format',
            field=models.CharField(choices=[('mp4', 'mp4, using mpeg4 codec'), ('avi', 'avi, using mpeg4 codec'), ('mkv', 'mkv, using libvpx codec'), ('3gp', '3gp, using h263 codec')], default='mp4', max_length=3, verbose_name='The format this video should be converted to.'),
        ),
    ]
